화상채팅 레이아웃
team-gu/service pull request #45
Opened 2021-07-27 08:52 UTC by minho-jang

| resolve [#S05P12A202-309](https://jira.ssafy.com/browse/S05P12A202-309), [#S05P12A202-310](https://jira.ssafy.com/browse/S05P12A202-310)

-  화상채팅 사용자 화면 배치
- 사용자 화면 좌측상단 닉네임 표시
- 비디오 비활성화 시 프로필이미지 표시
- 툴바 하단 배치

https://team-gu.github.io/service/feature/309/?path=/story/webrtc-video-chat-toolbar--video-chat-toolbar

작업을 하다보니 여러 이슈들을 합쳐서 진행하게 된거 같습니다. 다음에는 좀 더 잘게 쪼개서 PR 올리겠습니다. **feat** 커밋만 보셔도 무방합니다.

2021-07-27 10:05 UTC, dididy requested changes
몇가지 코멘트 남겼습니다.

서버가 로컬로 되어있어서 스토리북으로 확인했는데 레이아웃을 잘 구현하신 것 같습니다.

수고하셨습니다~!

2021-07-27 10:05 UTC, dididy commented on FE/components/webrtc/VideoChatLayout.stories.tsx
> +//   }}
앞으로 사용하지 않을 부분이라면 지우는게 좋아보입니다

2021-07-27 10:05 UTC, dididy commented on FE/components/webrtc/VideoChatLayout.stories.tsx
> +// 9 ~
arr이 상수라면 대문자로 표기하는건 어떨까요?

2021-07-27 14:13 UTC, minho-jang commented on FE/components/webrtc/VideoChatLayout.stories.tsx
> +//   }}
아아 넵 삭제했습니다.

2021-07-27 14:16 UTC, minho-jang commented on FE/components/webrtc/VideoChatLayout.stories.tsx
> +// 9 ~
스토리북에 인자를 주는 방식으로 수정했습니다.

2021-07-27 14:51 UTC, dididy approved these changes

2021-07-28 05:56 UTC, Dongkyun-Jang approved these changes
수고하셨습니다!!!

2021-07-28 06:26 UTC, merged